-- SQLite schema extracted from 1234.db.json
-- Generated by scripts/json-to-sqlite-schema.ts

-- teams
CREATE TABLE IF NOT EXISTS teams (
  number INTEGER NOT NULL PRIMARY KEY,
  advancement INTEGER NOT NULL,
  division INTEGER NOT NULL,
  inspire_eligible INTEGER NOT NULL,
  promote_eligible INTEGER NOT NULL,
  competing TEXT NOT NULL
);

-- formRows
CREATE TABLE IF NOT EXISTS form_rows (
  form_id TEXT NOT NULL,
  row INTEGER NOT NULL,
  type TEXT NOT NULL,
  column_count INTEGER NOT NULL,
  description TEXT NOT NULL,
  rule TEXT
);

-- formItems
CREATE TABLE IF NOT EXISTS form_items (
  form_id TEXT NOT NULL,
  row INTEGER NOT NULL,
  item_index INTEGER NOT NULL,
  label TEXT,
  type TEXT,
  automation_data TEXT,
  options TEXT
);

-- status
CREATE TABLE IF NOT EXISTS status (
  team INTEGER NOT NULL,
  stage TEXT NOT NULL,
  status INTEGER NOT NULL
);

-- practiceMatchSchedule
CREATE TABLE IF NOT EXISTS practice_match_schedule (
  start INTEGER NOT NULL,
  end INTEGER NOT NULL,
  type INTEGER NOT NULL,
  label TEXT NOT NULL
);

-- practiceBlocks
CREATE TABLE IF NOT EXISTS practice_blocks (
  start INTEGER NOT NULL,
  end INTEGER NOT NULL,
  type TEXT NOT NULL,
  cycle_time INTEGER NOT NULL,
  label TEXT
);

-- matchSchedule
CREATE TABLE IF NOT EXISTS match_schedule (
  start INTEGER NOT NULL,
  end INTEGER NOT NULL,
  type INTEGER NOT NULL,
  label TEXT NOT NULL
);

-- blocks
CREATE TABLE IF NOT EXISTS blocks (
  start INTEGER NOT NULL,
  end INTEGER NOT NULL,
  type TEXT NOT NULL,
  cycle_time INTEGER NOT NULL,
  label TEXT
);

-- selections
CREATE TABLE IF NOT EXISTS selections (
  id INTEGER NOT NULL PRIMARY KEY,
  op INTEGER NOT NULL,
  method INTEGER NOT NULL,
  team INTEGER NOT NULL
);

-- alliances
CREATE TABLE IF NOT EXISTS alliances (
  rank INTEGER NOT NULL,
  team1 INTEGER NOT NULL,
  team2 INTEGER NOT NULL,
  team3 INTEGER NOT NULL
);

-- practice
CREATE TABLE IF NOT EXISTS practice (
  match INTEGER NOT NULL,
  red1 INTEGER NOT NULL,
  red1s INTEGER NOT NULL,
  red2 INTEGER NOT NULL,
  red2s INTEGER NOT NULL,
  blue1 INTEGER NOT NULL,
  blue1s INTEGER NOT NULL,
  blue2 INTEGER NOT NULL,
  blue2s INTEGER NOT NULL
);

-- practiceData
CREATE TABLE IF NOT EXISTS practice_data (
  match INTEGER NOT NULL,
  status INTEGER NOT NULL,
  randomization INTEGER NOT NULL,
  start INTEGER NOT NULL,
  schedule_start INTEGER NOT NULL,
  posted_time INTEGER NOT NULL,
  fms_match_id TEXT NOT NULL,
  fms_schedule_detail_id TEXT NOT NULL
);

-- quals
CREATE TABLE IF NOT EXISTS quals (
  match INTEGER NOT NULL,
  red1 INTEGER NOT NULL,
  red1s INTEGER NOT NULL,
  red2 INTEGER NOT NULL,
  red2s INTEGER NOT NULL,
  blue1 INTEGER NOT NULL,
  blue1s INTEGER NOT NULL,
  blue2 INTEGER NOT NULL,
  blue2s INTEGER NOT NULL
);

-- qualsData
CREATE TABLE IF NOT EXISTS quals_data (
  match INTEGER NOT NULL,
  status INTEGER NOT NULL,
  randomization INTEGER NOT NULL,
  start INTEGER NOT NULL,
  schedule_start INTEGER NOT NULL,
  posted_time INTEGER NOT NULL,
  fms_match_id TEXT NOT NULL,
  fms_schedule_detail_id TEXT NOT NULL
);

-- qualsResults
CREATE TABLE IF NOT EXISTS quals_results (
  match INTEGER NOT NULL PRIMARY KEY,
  red_score INTEGER NOT NULL,
  blue_score INTEGER NOT NULL,
  red_penalty_committed INTEGER NOT NULL,
  blue_penalty_committed INTEGER NOT NULL
);

-- qualsScores
CREATE TABLE IF NOT EXISTS quals_scores (
  match INTEGER NOT NULL,
  alliance INTEGER NOT NULL,
  card1 INTEGER NOT NULL,
  card2 INTEGER NOT NULL,
  dq1 INTEGER NOT NULL,
  dq2 INTEGER NOT NULL,
  noshow1 INTEGER NOT NULL,
  noshow2 INTEGER NOT NULL,
  major INTEGER NOT NULL,
  minor INTEGER NOT NULL,
  adjust INTEGER NOT NULL
);

-- qualsGameSpecific
CREATE TABLE IF NOT EXISTS quals_game_specific (
  match INTEGER NOT NULL,
  alliance INTEGER NOT NULL,
  auto_classified_artifacts INTEGER NOT NULL,
  auto_overflow_artifacts INTEGER NOT NULL,
  auto_classifier_state TEXT NOT NULL,
  robot1auto INTEGER NOT NULL,
  robot2auto INTEGER NOT NULL,
  teleop_classified_artifacts INTEGER NOT NULL,
  teleop_overflow_artifacts INTEGER NOT NULL,
  teleop_depot_artifacts INTEGER NOT NULL,
  teleop_classifier_state TEXT NOT NULL,
  robot1teleop INTEGER NOT NULL,
  robot2teleop INTEGER NOT NULL,
  violations TEXT NOT NULL,
  own_major INTEGER NOT NULL,
  own_minor INTEGER NOT NULL,
  other_major INTEGER NOT NULL,
  other_minor INTEGER NOT NULL,
  hr_major INTEGER NOT NULL,
  hr_minor INTEGER NOT NULL
);

-- elims
CREATE TABLE IF NOT EXISTS elims (
  match INTEGER NOT NULL,
  red INTEGER NOT NULL,
  blue INTEGER NOT NULL
);

-- elimsData
CREATE TABLE IF NOT EXISTS elims_data (
  match INTEGER NOT NULL,
  status INTEGER NOT NULL,
  randomization INTEGER NOT NULL,
  start INTEGER NOT NULL,
  posted_time INTEGER NOT NULL,
  fms_match_id TEXT NOT NULL,
  fms_schedule_detail_id TEXT NOT NULL
);

-- elimsResults
CREATE TABLE IF NOT EXISTS elims_results (
  match INTEGER NOT NULL,
  red_score INTEGER NOT NULL,
  blue_score INTEGER NOT NULL,
  red_penalty_committed INTEGER NOT NULL,
  blue_penalty_committed INTEGER NOT NULL
);

-- elimsScores
CREATE TABLE IF NOT EXISTS elims_scores (
  match INTEGER NOT NULL,
  alliance INTEGER NOT NULL,
  card INTEGER NOT NULL,
  dq INTEGER NOT NULL,
  noshow1 INTEGER NOT NULL,
  noshow2 INTEGER NOT NULL,
  noshow3 INTEGER NOT NULL,
  major INTEGER NOT NULL,
  minor INTEGER NOT NULL,
  adjust INTEGER NOT NULL
);

-- elimsGameSpecific
CREATE TABLE IF NOT EXISTS elims_game_specific (
  match INTEGER NOT NULL,
  alliance INTEGER NOT NULL,
  auto_classified_artifacts INTEGER NOT NULL,
  auto_overflow_artifacts INTEGER NOT NULL,
  auto_classifier_state TEXT NOT NULL,
  robot1auto INTEGER NOT NULL,
  robot2auto INTEGER NOT NULL,
  teleop_classified_artifacts INTEGER NOT NULL,
  teleop_overflow_artifacts INTEGER NOT NULL,
  teleop_depot_artifacts INTEGER NOT NULL,
  teleop_classifier_state TEXT NOT NULL,
  robot1teleop INTEGER NOT NULL,
  robot2teleop INTEGER NOT NULL,
  violations TEXT NOT NULL,
  own_major INTEGER NOT NULL,
  own_minor INTEGER NOT NULL,
  other_major INTEGER NOT NULL,
  other_minor INTEGER NOT NULL,
  hr_major INTEGER NOT NULL,
  hr_minor INTEGER NOT NULL
);

-- qualsCommitHistory
CREATE TABLE IF NOT EXISTS quals_commit_history (
  match INTEGER NOT NULL,
  ts INTEGER NOT NULL,
  start INTEGER NOT NULL,
  random INTEGER NOT NULL,
  type INTEGER NOT NULL
);

-- elimsCommitHistory
CREATE TABLE IF NOT EXISTS elims_commit_history (
  match INTEGER NOT NULL,
  ts INTEGER NOT NULL,
  start INTEGER NOT NULL,
  random INTEGER NOT NULL,
  type INTEGER NOT NULL
);

-- qualsScoresHistory
CREATE TABLE IF NOT EXISTS quals_scores_history (
  match INTEGER NOT NULL,
  ts INTEGER NOT NULL,
  alliance INTEGER NOT NULL,
  card1 INTEGER NOT NULL,
  card2 INTEGER NOT NULL,
  dq1 INTEGER NOT NULL,
  dq2 INTEGER NOT NULL,
  noshow1 INTEGER NOT NULL,
  noshow2 INTEGER NOT NULL,
  major INTEGER NOT NULL,
  minor INTEGER NOT NULL,
  adjust INTEGER NOT NULL
);

-- qualsGameSpecificHistory
CREATE TABLE IF NOT EXISTS quals_game_specific_history (
  match INTEGER NOT NULL,
  ts INTEGER NOT NULL,
  alliance INTEGER NOT NULL,
  auto_classified_artifacts INTEGER NOT NULL,
  auto_overflow_artifacts INTEGER NOT NULL,
  auto_classifier_state TEXT NOT NULL,
  robot1auto INTEGER NOT NULL,
  robot2auto INTEGER NOT NULL,
  teleop_classified_artifacts INTEGER NOT NULL,
  teleop_overflow_artifacts INTEGER NOT NULL,
  teleop_depot_artifacts INTEGER NOT NULL,
  teleop_classifier_state TEXT NOT NULL,
  robot1teleop INTEGER NOT NULL,
  robot2teleop INTEGER NOT NULL,
  violations TEXT NOT NULL,
  own_major INTEGER NOT NULL,
  own_minor INTEGER NOT NULL,
  other_major INTEGER NOT NULL,
  other_minor INTEGER NOT NULL,
  hr_major INTEGER NOT NULL,
  hr_minor INTEGER NOT NULL
);

-- elimsScoresHistory
CREATE TABLE IF NOT EXISTS elims_scores_history (
  match INTEGER NOT NULL,
  ts INTEGER NOT NULL,
  alliance INTEGER NOT NULL,
  card INTEGER NOT NULL,
  dq INTEGER NOT NULL,
  noshow1 INTEGER NOT NULL,
  noshow2 INTEGER NOT NULL,
  noshow3 INTEGER NOT NULL,
  major INTEGER NOT NULL,
  minor INTEGER NOT NULL,
  adjust INTEGER NOT NULL
);

-- elimsGameSpecificHistory
CREATE TABLE IF NOT EXISTS elims_game_specific_history (
  match INTEGER NOT NULL,
  ts INTEGER NOT NULL,
  alliance INTEGER NOT NULL,
  auto_classified_artifacts INTEGER NOT NULL,
  auto_overflow_artifacts INTEGER NOT NULL,
  auto_classifier_state TEXT NOT NULL,
  robot1auto INTEGER NOT NULL,
  robot2auto INTEGER NOT NULL,
  teleop_classified_artifacts INTEGER NOT NULL,
  teleop_overflow_artifacts INTEGER NOT NULL,
  teleop_depot_artifacts INTEGER NOT NULL,
  teleop_classifier_state TEXT NOT NULL,
  robot1teleop INTEGER NOT NULL,
  robot2teleop INTEGER NOT NULL,
  violations TEXT NOT NULL,
  own_major INTEGER NOT NULL,
  own_minor INTEGER NOT NULL,
  other_major INTEGER NOT NULL,
  other_minor INTEGER NOT NULL,
  hr_major INTEGER NOT NULL,
  hr_minor INTEGER NOT NULL
);

-- inspectionScheduleForm
CREATE TABLE IF NOT EXISTS inspection_schedule_form (
  id INTEGER NOT NULL,
  str TEXT NOT NULL
);

-- inspectionScheduleItems
CREATE TABLE IF NOT EXISTS inspection_schedule_items (
  id INTEGER NOT NULL,
  team INTEGER NOT NULL,
  name TEXT NOT NULL,
  station_number INTEGER NOT NULL,
  start_time INTEGER NOT NULL,
  total_time INTEGER NOT NULL,
  month INTEGER NOT NULL,
  day INTEGER NOT NULL,
  year INTEGER NOT NULL
);

-- sponsors
CREATE TABLE IF NOT EXISTS sponsors (
  sponsor_id TEXT NOT NULL,
  name TEXT NOT NULL,
  title TEXT NOT NULL,
  position INTEGER NOT NULL,
  logo TEXT NOT NULL,
  level INTEGER NOT NULL
);

-- config
CREATE TABLE IF NOT EXISTS config (
  key TEXT NOT NULL PRIMARY KEY,
  value TEXT
);

-- hrMeetingNotes
CREATE TABLE IF NOT EXISTS hr_meeting_notes (
  type TEXT NOT NULL,
  content TEXT NOT NULL
);

-- systemSurveySamples
CREATE TABLE IF NOT EXISTS system_survey_samples (
  survey_type TEXT NOT NULL,
  sample_time INTEGER NOT NULL,
  sample_description TEXT NOT NULL,
  data TEXT NOT NULL
);

-- Award
CREATE TABLE IF NOT EXISTS award (
  fms_award_id TEXT NOT NULL PRIMARY KEY,
  fms_season_id TEXT NOT NULL,
  award_id INTEGER NOT NULL,
  award_subtype_id INTEGER NOT NULL,
  tournament_type INTEGER NOT NULL,
  type INTEGER NOT NULL,
  culture_type INTEGER NOT NULL,
  description TEXT NOT NULL,
  default_quantity TEXT,
  sponsor_details TEXT,
  display_order_ui INTEGER NOT NULL,
  display_order_online INTEGER NOT NULL,
  cmp_qualifying INTEGER NOT NULL,
  allow_manual_entry INTEGER NOT NULL,
  created_on TEXT NOT NULL,
  created_by TEXT,
  modified_on TEXT NOT NULL,
  modified_by TEXT,
  script TEXT NOT NULL,
  can_edit INTEGER NOT NULL
);

-- AwardAssignment
CREATE TABLE IF NOT EXISTS award_assignment (
  fms_award_id TEXT NOT NULL,
  fms_event_id TEXT NOT NULL,
  series INTEGER NOT NULL,
  fms_team_id TEXT,
  first_name TEXT,
  last_name TEXT,
  is_public INTEGER NOT NULL,
  created_on TEXT NOT NULL,
  created_by TEXT NOT NULL,
  modified_on TEXT,
  modified_by TEXT,
  comment TEXT
);

-- TeamRanking
CREATE TABLE IF NOT EXISTS team_ranking (
  fms_event_id TEXT NOT NULL,
  fms_team_id TEXT NOT NULL,
  ranking INTEGER NOT NULL,
  rank_change INTEGER NOT NULL,
  wins INTEGER NOT NULL,
  losses INTEGER NOT NULL,
  ties INTEGER NOT NULL,
  qualifying_score TEXT NOT NULL,
  points_scored_total REAL NOT NULL,
  points_scored_average TEXT NOT NULL,
  points_scored_average_change INTEGER NOT NULL,
  matches_played INTEGER NOT NULL,
  matches_counted INTEGER NOT NULL,
  disqualified INTEGER NOT NULL,
  sort_order1 TEXT NOT NULL,
  sort_order2 TEXT NOT NULL,
  sort_order3 TEXT NOT NULL,
  sort_order4 TEXT NOT NULL,
  sort_order5 TEXT NOT NULL,
  sort_order6 TEXT NOT NULL,
  modified_on TEXT NOT NULL
);

-- Team
CREATE TABLE IF NOT EXISTS team (
  fms_team_id TEXT NOT NULL,
  fms_season_id TEXT,
  fms_region_id TEXT,
  team_id INTEGER NOT NULL,
  team_number INTEGER NOT NULL,
  team_name_long TEXT,
  team_name_short TEXT NOT NULL,
  robot_name TEXT,
  city TEXT NOT NULL,
  state_prov TEXT NOT NULL,
  country TEXT NOT NULL,
  website TEXT,
  rookie_year INTEGER NOT NULL,
  was_added_from_ui INTEGER NOT NULL,
  cmp_prequalified INTEGER NOT NULL,
  school_name TEXT,
  demo_team INTEGER NOT NULL,
  paid INTEGER NOT NULL,
  fms_home_cmp_id TEXT,
  game_specifics TEXT,
  created_on TEXT NOT NULL,
  created_by TEXT NOT NULL,
  modified_on TEXT NOT NULL,
  modified_by TEXT NOT NULL
);

-- ScheduleDetail
CREATE TABLE IF NOT EXISTS schedule_detail (
  fms_schedule_detail_id TEXT NOT NULL,
  fms_event_id TEXT NOT NULL,
  tournament_level INTEGER NOT NULL,
  match_number INTEGER NOT NULL,
  field_type INTEGER NOT NULL,
  description TEXT NOT NULL,
  start_time TEXT NOT NULL,
  field_configuration_details TEXT,
  created_on TEXT,
  created_by TEXT NOT NULL,
  modified_on TEXT,
  modified_by TEXT,
  row_version TEXT NOT NULL
);

-- ScheduleStation
CREATE TABLE IF NOT EXISTS schedule_station (
  fms_schedule_detail_id TEXT NOT NULL,
  alliance INTEGER NOT NULL,
  station INTEGER NOT NULL,
  fms_event_id TEXT NOT NULL,
  fms_team_id TEXT NOT NULL,
  is_surrogate INTEGER NOT NULL,
  created_on TEXT,
  created_by TEXT NOT NULL,
  modified_on TEXT,
  modified_by TEXT
);

-- Match
CREATE TABLE IF NOT EXISTS match (
  fms_match_id TEXT NOT NULL,
  fms_schedule_detail_id TEXT NOT NULL,
  play_number INTEGER NOT NULL,
  field_type INTEGER NOT NULL,
  initial_pre_start_time TEXT,
  final_pre_start_time TEXT,
  pre_start_count INTEGER NOT NULL,
  auto_start_time TEXT NOT NULL,
  auto_end_time TEXT NOT NULL,
  teleop_start_time TEXT NOT NULL,
  teleop_end_time TEXT,
  ref_commit_time TEXT,
  score_keeper_commit_time TEXT NOT NULL,
  post_match_time TEXT,
  cancel_match_time TEXT,
  cycle_time TEXT,
  red_score INTEGER NOT NULL,
  blue_score INTEGER NOT NULL,
  red_penalty INTEGER NOT NULL,
  blue_penalty INTEGER NOT NULL,
  red_auto_score INTEGER NOT NULL,
  blue_auto_score INTEGER NOT NULL,
  score_details TEXT NOT NULL,
  head_ref_review INTEGER NOT NULL,
  video_url TEXT,
  created_on TEXT NOT NULL,
  created_by TEXT NOT NULL,
  modified_on TEXT NOT NULL,
  modified_by TEXT NOT NULL,
  fms_event_id TEXT,
  row_version TEXT NOT NULL
);

-- _patches
CREATE TABLE IF NOT EXISTS patches (
  patch_id TEXT NOT NULL,
  db_version INTEGER NOT NULL,
  patch TEXT NOT NULL,
  applied INTEGER NOT NULL
);

-- advancementPoints
CREATE TABLE IF NOT EXISTS advancement_points (
  team INTEGER NOT NULL,
  sort_tuple TEXT NOT NULL,
  private_points INTEGER NOT NULL
);